version: '3.6'

secrets:
  ledger_git:
    file: ledger-git

configs:
  fava:
    file: user.conf

services:
  fava:
    image: fava-service:latest
    container_name: fava
    ports:
      - 80:80
    secrets:
      - ledger_git
    configs:
      - source: fava
        target: /etc/user.conf
    restart: always
